# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(777, 653)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/签到.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Register.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Register)
        self.frame.setGeometry(QtCore.QRect(10, 10, 751, 371))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ShowLb = QtWidgets.QLabel(self.frame)
        self.ShowLb.setGeometry(QtCore.QRect(80, 10, 581, 341))
        self.ShowLb.setText("")
        self.ShowLb.setPixmap(QtGui.QPixmap(":/newPrefix/tips.jpg"))
        self.ShowLb.setObjectName("ShowLb")
        self.frame_2 = QtWidgets.QFrame(Register)
        self.frame_2.setGeometry(QtCore.QRect(10, 400, 751, 241))
        self.frame_2.setStatusTip("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 150, 431, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StartBt = QtWidgets.QPushButton(self.layoutWidget)
        self.StartBt.setObjectName("StartBt")
        self.horizontalLayout.addWidget(self.StartBt)
        self.PhotoBt = QtWidgets.QPushButton(self.layoutWidget)
        self.PhotoBt.setObjectName("PhotoBt")
        self.horizontalLayout.addWidget(self.PhotoBt)
        self.RegisterBt = QtWidgets.QPushButton(self.layoutWidget)
        self.RegisterBt.setObjectName("RegisterBt")
        self.horizontalLayout.addWidget(self.RegisterBt)
        self.ModelBt = QtWidgets.QPushButton(self.layoutWidget)
        self.ModelBt.setObjectName("ModelBt")
        self.horizontalLayout.addWidget(self.ModelBt)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 100, 211, 118))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stu_id = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.stu_id.setFont(font)
        self.stu_id.setStatusTip("")
        self.stu_id.setText("")
        self.stu_id.setObjectName("stu_id")
        self.verticalLayout.addWidget(self.stu_id)
        self.stu_name = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stu_name.setFont(font)
        self.stu_name.setObjectName("stu_name")
        self.verticalLayout.addWidget(self.stu_name)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setGeometry(QtCore.QRect(280, 100, 461, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.MsgLb = QtWidgets.QLabel(self.frame_2)
        self.MsgLb.setGeometry(QtCore.QRect(290, 20, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.MsgLb.setFont(font)
        self.MsgLb.setStatusTip("")
        self.MsgLb.setText("")
        self.MsgLb.setObjectName("MsgLb")

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "注册"))
        self.StartBt.setText(_translate("Register", "新建"))
        self.PhotoBt.setText(_translate("Register", "拍照"))
        self.RegisterBt.setText(_translate("Register", "注册"))
        self.ModelBt.setText(_translate("Register", "模型训练"))
        self.label_2.setText(_translate("Register", "学号："))
        self.label.setText(_translate("Register", "姓名："))
import icon.icon_rc
